services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: anon
      POSTGRES_PASSWORD: anon
      POSTGRES_DB: anontma
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    command: redis-server --maxmemory-policy noeviction
    ports:
      - "6379:6379"

volumes:
  postgres-data:
